name: Deploy to Surge

on:
  push:
    branches:  [ main, develop ]
  workflow_dispatch: # Allows you to run the workflow manually

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run test
        run: npm test

      - name: Install Surge
        run: npm install --global surge

      - name: Build the application
        run: npm run build

      - name: Run the application
        run: npm run dev &

      - name: Cypress -- Run tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./tests
          wait-on: "http://localhost:5173"

      - name: Deploy to Surge
        run: surge --project ./dist --domain demonstration-2602.surge.sh
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

